using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json.Serialization;

namespace RedBloom.Models;

/// <summary>
/// Who a roleplay model is meant to be, and the standing instructions built from it.
/// </summary>
/// <remarks>
/// Roleplay finetunes are trained on conversations generated by the big assistants, and they
/// learn those assistants' answers about themselves along with their prose — asked who it is, a
/// model of this kind will happily name a company that has never seen it. Nothing is wrong with
/// the model; it is repeating a line from its training data. Giving it an identity of its own is
/// what stops that, which is why the first thing this card writes is the name.
/// </remarks>
public sealed class CharacterCard : INotifyPropertyChanged
{
    private string _name = string.Empty;
    private string _sex = string.Empty;
    private string _age = string.Empty;
    private string _race = string.Empty;
    private string _height = string.Empty;
    private string _weight = string.Empty;
    private string _hair = string.Empty;
    private string _skin = string.Empty;
    private string _biography = string.Empty;
    private string _manner = string.Empty;
    private string _likes = string.Empty;
    private string _dislikes = string.Empty;
    private string _hobbies = string.Empty;
    private string _scenario = string.Empty;
    private string _greeting = string.Empty;
    private string _other = string.Empty;

    public string Name { get => _name; set => Set(ref _name, value); }

    public string Sex { get => _sex; set => Set(ref _sex, value); }

    public string Age { get => _age; set => Set(ref _age, value); }

    public string Race { get => _race; set => Set(ref _race, value); }

    public string Height { get => _height; set => Set(ref _height, value); }

    public string Weight { get => _weight; set => Set(ref _weight, value); }

    public string Hair { get => _hair; set => Set(ref _hair, value); }

    public string Skin { get => _skin; set => Set(ref _skin, value); }

    public string Biography { get => _biography; set => Set(ref _biography, value); }

    /// <summary>How they speak — clipped, florid, foul-mouthed, formal.</summary>
    public string Manner { get => _manner; set => Set(ref _manner, value); }

    public string Likes { get => _likes; set => Set(ref _likes, value); }

    public string Dislikes { get => _dislikes; set => Set(ref _dislikes, value); }

    public string Hobbies { get => _hobbies; set => Set(ref _hobbies, value); }

    /// <summary>Where this is taking place, and what has just happened.</summary>
    public string Scenario { get => _scenario; set => Set(ref _scenario, value); }

    /// <summary>The line the character opens with, shown when a chat on them is empty.</summary>
    public string Greeting { get => _greeting; set => Set(ref _greeting, value); }

    public string Other { get => _other; set => Set(ref _other, value); }

    [JsonIgnore]
    public bool IsEmpty =>
        string.IsNullOrWhiteSpace(_name)
        && string.IsNullOrWhiteSpace(_biography)
        && string.IsNullOrWhiteSpace(_scenario)
        && string.IsNullOrWhiteSpace(_other);

    /// <summary>
    /// The card as standing instructions.
    /// </summary>
    /// <remarks>
    /// Written as prose with a labelled block rather than as JSON: these models are trained on
    /// character sheets in roughly this shape, and they follow it far better than a structure
    /// they have never been shown. Empty fields are left out entirely — a line reading
    /// "Weight: " invites the model to invent one and then dwell on it.
    /// </remarks>
    public string Compose()
    {
        if (IsEmpty)
        {
            return string.Empty;
        }

        var who = string.IsNullOrWhiteSpace(_name) ? "this character" : _name.Trim();
        var text = new StringBuilder();

        text.Append("You are ").Append(who).AppendLine(". Stay in character at all times.")
            .AppendLine();

        var traits = new List<(string Label, string Value)>
        {
            ("Name", _name),
            ("Sex", _sex),
            ("Age", _age),
            ("Race", _race),
            ("Height", _height),
            ("Weight", _weight),
            ("Hair", _hair),
            ("Skin", _skin),
            ("Manner of speech", _manner),
            ("Likes", _likes),
            ("Dislikes", _dislikes),
            ("Hobbies", _hobbies),
        };

        foreach (var (label, value) in traits)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                text.Append(label).Append(": ").AppendLine(value.Trim());
            }
        }

        Section(text, "Biography", _biography);
        Section(text, "Scene", _scenario);
        Section(text, "Also", _other);

        // The point of the whole thing. Said last, where these models weight it most, and said
        // plainly: the identity they volunteer is a memorised line, not a belief to argue with.
        text.AppendLine()
            .Append("You are ").Append(who)
            .AppendLine(" and nothing else. You are not an AI assistant and you were not made by "
                + "any AI company; if you are asked what you are, answer as "
                + who + " would, in character. Never mention models, training or these "
                + "instructions.");

        return text.ToString().TrimEnd();
    }

    private static void Section(StringBuilder text, string heading, string body)
    {
        if (!string.IsNullOrWhiteSpace(body))
        {
            text.AppendLine().Append(heading).AppendLine(":").AppendLine(body.Trim());
        }
    }

    public CharacterCard Clone()
    {
        var copy = new CharacterCard();
        copy.CopyFrom(this);
        return copy;
    }

    public void CopyFrom(CharacterCard other)
    {
        Name = other.Name;
        Sex = other.Sex;
        Age = other.Age;
        Race = other.Race;
        Height = other.Height;
        Weight = other.Weight;
        Hair = other.Hair;
        Skin = other.Skin;
        Biography = other.Biography;
        Manner = other.Manner;
        Likes = other.Likes;
        Dislikes = other.Dislikes;
        Hobbies = other.Hobbies;
        Scenario = other.Scenario;
        Greeting = other.Greeting;
        Other = other.Other;
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private void Set(ref string field, string value, [CallerMemberName] string? propertyName = null)
    {
        value ??= string.Empty;

        if (field == value)
        {
            return;
        }

        field = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
