using System.Windows;
using RedBloom.Models;

namespace RedBloom.Services;

/// <summary>
/// Holds every user-facing string in each language and pushes the chosen set into the
/// application resources.
/// </summary>
/// <remarks>
/// The strings go in under <c>L_*</c> keys, and the XAML reads them with DynamicResource, so
/// swapping the language re-points every label at once with no per-control wiring. Code-behind
/// that builds text itself reads through <see cref="T"/> and rebuilds on <see cref="Changed"/>.
/// </remarks>
public static class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        // ---- main window chrome ----
        ["L_CloseTabTip"] = "Close tab (Ctrl+Shift+W)",
        ["L_Edit"] = "Edit",
        ["L_Delete"] = "Delete",
        ["L_CollapseSidebarTip"] = "Collapse the sidebar (Ctrl+Shift+B)",
        ["L_NewTabTip"] = "New tab (Ctrl+Shift+T)",
        ["L_ChooseShell"] = "Choose a shell",
        ["L_TabCard"] = "Tab card",
        ["L_CardColor"] = "Colour",
        ["L_CardOpacity"] = "Opacity",
        ["L_CardBlur"] = "Blur",
        ["L_CardImage"] = "Picture",
        ["L_CardIcon"] = "Icon (Segoe glyph)",
        ["L_CardReset"] = "Reset",
        ["L_CardRightClickHint"] = "Right-click a tab to change its colour, opacity and blur.",
        ["L_SplitSameTip"] = "Split: another shell on this SSH connection (Ctrl+Alt+D)",
        ["L_SplitNewTip"] = "Split: a new session alongside (Ctrl+Shift+D)",
        ["L_CloseSplitTip"] = "Close this split (Ctrl+Alt+A)",
        ["L_Minimize"] = "Minimize",
        ["L_Maximize"] = "Maximize",
        ["L_Close"] = "Close",
        ["L_MinimizeToTray"] = "Hide to the tray",
        ["L_TrayShow"] = "Show RedBloom",
        ["L_TrayExit"] = "Exit",
        ["L_RestartAdmin"] = "Restart as administrator",
        ["L_ElevateNow"] = "Gain administrator rights",
        ["L_ElevateReady"] = "Administrator rights are ready. Commands that ask for them now run elevated.",
        ["L_AlreadyAdmin"] = "Running as administrator",
        ["L_SshSessions"] = "SSH SESSIONS",
        ["L_NewSshSession"] = "New SSH session",
        ["L_SaveThisSession"] = "Save this connection to the sidebar?",
        ["L_SaveToastSaved"] = "Saved “{0}”.",
        ["L_Dismiss"] = "Dismiss",
        ["L_FilterHint"] = "Filter…",
        ["L_NoSavedSessions"] = "No saved sessions",
        ["L_UsePlusToAdd"] = "Use + above to add one",
        ["L_NoOpenTerminals"] = "No open terminals",
        ["L_EmptyHint"] = "Ctrl+Shift+T for a new tab  ·  double-click a session to connect",
        ["L_Settings"] = "Settings",
        ["L_AiSettings"] = "AI settings",

        // ---- AI agents ----
        ["L_AiTitle"] = "AI agents",
        ["L_AiNote"] = "Each agent is an endpoint, a model and a set of standing instructions. "
                       + "Run one and it opens as a tab, like a shell or an SSH session.",
        ["L_AiAdd"] = "Add",
        ["L_AiDelete"] = "Delete",
        ["L_AiNewAgent"] = "New agent",
        ["L_AiName"] = "Name",
        ["L_AiProvider"] = "API",
        ["L_AiOpenAiCompatible"] = "OpenAI-compatible",
        ["L_AiClaudeCli"] = "Claude Code (CLI)",
        ["L_AiClaudeCliNote"] = "Uses the installed Claude Code command-line tool. It signs in on its "
                               + "own and picks its own model, so there is no endpoint, key or model to set.",
        ["L_AiAddLocal"] = "＋ Local model",
        ["L_AiAddLocalNone"] = "No local models found on this machine",
        ["L_AiAddLocalAll"] = "All local models are already added",
        ["L_AiLocalModelNote"] = "A model on this machine ({0}). The engine is started on the first "
                                + "message; there is no endpoint or key to set.",
        ["L_AiBaseUrl"] = "Endpoint",
        ["L_AiBaseUrlNote"] = "Leave empty for the provider's own. Requests go to {0}.",
        ["L_AiApiKey"] = "API key",
        ["L_AiModel"] = "Model",
        ["L_AiAvatar"] = "Avatar",
        ["L_AiNameColor"] = "Name colour",
        ["L_AiMaxTokens"] = "Reply limit (tokens)",
        ["L_AiContextWindow"] = "Context window (tokens)",
        ["L_AiContextWindowNote"] = "How much the model can hold at once. Drives the gauge under the "
                                    + "chat, and the point at which the earlier part of a conversation "
                                    + "is folded into a summary.",
        ["L_AiEffort"] = "Effort",
        ["L_AiThinking"] = "Let the model think first",
        ["L_AiThinkingNote"] = "Adaptive: the model decides per question how much thought it is worth. "
                               + "The reasoning itself is never returned, so a thinking turn shows as a pause.",
        ["L_AiAllowCommands"] = "Let this agent run commands",
        ["L_AiAllowCommandsNote"] = "The agent gets a tool that runs command lines on this machine, "
                                    + "with everything your account can do. What it decides to run is "
                                    + "shaped by whatever it has read along the way, so leave the "
                                    + "approval prompt on unless you are watching the session.",
        ["L_AiAskBeforeRun"] = "Ask before each command",
        ["L_AiAllowAgents"] = "Let this agent call other agents",
        ["L_AiAllowAgentsNote"] = "The agent gets a tool that hands a request to another of your agents "
                                  + "by name and gets back what it made — most usefully an image agent, "
                                  + "which draws a picture. The agent it calls runs on its own, without "
                                  + "tools, so calls do not chain.",
        ["L_AiAllowImages"] = "Let this agent draw pictures",
        ["L_AiAllowImagesNote"] = "The agent gets a tool that draws a picture from a prompt with the "
                                  + "local image model (stable-diffusion.cpp) and shows it in the chat. "
                                  + "Needs the image engine installed and a diffusion .gguf in the AIModels folder.",
        ["L_AiImageEngineInstall"] = "Install image engine",
        ["L_AiImageEngineReinstall"] = "Reinstall / switch backend",
        ["L_AiImageEngineReady"] = "Image engine installed.",
        ["L_AiImageEngineInstalledFmt"] = "Installed: {0}.",
        ["L_AiImageEngineSuggest"] = "Not installed. Suggested for your hardware: {0}.",
        ["L_AiImageEngineInstalling"] = "Downloading… {0}%",
        ["L_AiImageEngineAsk"] = "Download the {0} build of stable-diffusion.cpp into {1}? It is a few "
                                 + "hundred megabytes and installs beside the program, needing no administrator.",
        ["L_AiPickModel"] = "Choose…",
        ["L_AiPickModelNone"] = "No local models found",
        ["L_AiImageModel"] = "Local image model",
        ["L_AiImageModelNote"] = "Which diffusion model to draw with. Found: {0}. Leave empty for the first one.",
        ["L_AiImageModelNoneNote"] = "No diffusion model was found in the AIModels folder. Put a diffusion .gguf there.",
        ["L_ImageAgentNoPrompt"] = "Type what to draw, and the model will draw it.",
        ["L_ImageAgentNoEngine"] = "The image engine is not installed. Install it under \"Let this agent draw pictures\".",
        ["L_ImageAgentNoModel"] = "No diffusion model was found for this agent.",
        ["L_AiAllowedCommands"] = "Allowed without asking",
        ["L_AiAllowedCommandsNote"] = "One per line. A line matches a command that is exactly it, "
                                      + "or that starts with it followed by a space — so \"git\" covers "
                                      + "every git call, \"git status\" only that one. Answering [a] at "
                                      + "the prompt adds a line here.",
        ["L_AiSystemPrompt"] = "Standing instructions",
        ["L_AiRoleplay"] = "Roleplay model (plays a character)",
        ["L_AiRoleplayNote"] = "The character card below is sent ahead of everything else, so the "
                               + "model answers as this character instead of naming whoever trained it. "
                               + "Empty fields are left out.",
        ["L_CharCard"] = "Character card",
        ["L_CharName"] = "Name",
        ["L_CharSex"] = "Sex",
        ["L_CharAge"] = "Age",
        ["L_CharRace"] = "Race",
        ["L_CharHeight"] = "Height",
        ["L_CharWeight"] = "Weight",
        ["L_CharHair"] = "Hair",
        ["L_CharSkin"] = "Skin",
        ["L_CharManner"] = "Manner of speech",
        ["L_CharLikes"] = "Likes",
        ["L_CharDislikes"] = "Dislikes",
        ["L_CharHobbies"] = "Hobbies",
        ["L_CharBiography"] = "Biography",
        ["L_CharScenario"] = "Scene",
        ["L_CharGreeting"] = "Greeting",
        ["L_CharOther"] = "Also",
        ["L_AiTest"] = "Test connection",
        ["L_AiTesting"] = "Checking…",
        ["L_AiTestOk"] = "The endpoint answered and accepted the key.",
        ["L_AiTestFailed"] = "Failed: {0}",
        ["L_AiLaunch"] = "Run",
        ["L_AiImport"] = "Import",
        ["L_AiImportTitle"] = "Import a config",
        ["L_AiImportNote"] = "Paste the settings of a command-line Claude tool — the object with an "
                             + "\"env\" block. One agent is created per model it names.",
        ["L_AiImportFromFile"] = "From a file…",
        ["L_AiImportAction"] = "Import",
        ["L_AiImportReading"] = "Reading the config…",
        ["L_AiImported"] = "Imported {0}.",
        ["L_AiChats"] = "CHATS",
        ["L_AiNewChat"] = "New chat",
        ["L_RoomsTab"] = "Rooms",
        ["L_RoomNone"] = "No rooms yet. Create one with the + above.",
        ["L_RoomNew"] = "New room",
        ["L_RoomTitle"] = "Room",
        ["L_RoomName"] = "Name",
        ["L_RoomParticipants"] = "Participants",
        ["L_RoomAvatarNone"] = "no picture",
        ["L_RoomKindImage"] = "images",
        ["L_RoomKindLocal"] = "local",
        ["L_RoomMode"] = "Who answers",
        ["L_RoomModerator"] = "Moderator",
        ["L_RoomOpen"] = "Open",
        ["L_RoomEdit"] = "Edit room",
        ["L_RoomEmpty"] = "This room has no participants. Add some in its settings.",
        ["L_RoomNeedAgents"] = "Add at least one agent to the room. Configure agents on the AI page first.",
        ["L_RoomUser"] = "User",
        ["L_RoomPolicyMention"] = "By @mention",
        ["L_RoomPolicyRoundRobin"] = "In turn",
        ["L_RoomPolicyAll"] = "Everyone",
        ["L_RoomPolicyModerator"] = "Moderator decides",
        ["L_RoomPolicyMentionNote"] = "Nobody answers until named with an @ — by you or by another agent. "
                                      + "The quietest room; you direct it.",
        ["L_RoomPolicyRoundRobinNote"] = "One agent answers each message, cycling through the list in order.",
        ["L_RoomPolicyAllNote"] = "Every agent answers each message, in the listed order.",
        ["L_RoomPolicyModeratorNote"] = "A moderator agent is asked who should speak next, until it decides "
                                        + "the exchange is done.",
        ["L_AiNoChats"] = "No chats with this agent yet",
        ["L_AiDeleteChat"] = "Delete this chat",
        ["L_AiChatName"] = "Chat name",
        ["L_AiChatNameNote"] = "Leave empty to name it after the first question again.",
        ["L_AiRenameChat"] = "Rename chat (F2)",
        ["L_AiBotName"] = "Agent's name here",
        ["L_AiBotNameNote"] = "Leave empty to use the agent's own name.",
        ["L_AiChatAvatar"] = "Avatar for this chat",
        ["L_AiChatAvatarNote"] = "Leave empty to use the agent's own picture.",

        // ---- settings: header ----
        ["L_Appearance"] = "Appearance",
        ["L_AppearanceNote"] = "Changes apply immediately and are saved as you go.",
        ["L_ResetDefaults"] = "Reset to defaults",

        // ---- settings: language ----
        ["L_Language"] = "Language",
        ["L_LanguageNote"] = "Language of the interface. Applies at once.",

        // ---- settings: integration ----
        ["L_Integration"] = "Integration",
        ["L_IntegrationNote"] = "Add RedBloom to Explorer so you can open a shell in any folder. Becoming the Windows default terminal needs a deeper OS integration and is not offered here.",
        ["L_OpenHere"] = "Open RedBloom here",
        ["L_OpenHereToggle"] = "Show \"Open RedBloom here\" in the folder context menu",

        // ---- settings: terminal text ----
        ["L_TerminalText"] = "Terminal text",
        ["L_TerminalTextNote"] = "Only fixed-width fonts are listed — a proportional font would break column alignment.",
        ["L_Font"] = "Font",
        ["L_Size"] = "Size",
        ["L_LineHeight"] = "Line height",
        ["L_Cursor"] = "Cursor",
        ["L_CursorBar"] = "Bar",
        ["L_CursorBlock"] = "Block",
        ["L_CursorUnderline"] = "Underline",
        ["L_Blink"] = "Blink",
        ["L_Scrollback"] = "Scrollback",

        // ---- settings: background picture ----
        ["L_BackgroundPicture"] = "Background picture",
        ["L_BackgroundPictureNote"] = "One picture behind the whole window, or a separate one per panel.",
        ["L_BgNone"] = "None",
        ["L_BgWindow"] = "Whole window",
        ["L_BgRegions"] = "Per panel",
        ["L_BgLive"] = "Live wallpaper",
        ["L_LiveNote"] = "Shows the desktop wallpaper itself, animation included — Wallpaper Engine scenes work. Blur, overlay and opacity below still apply.",
        ["L_Layout"] = "Layout",
        ["L_FollowDesktop"] = "Follow the desktop",
        ["L_FitInsideWindow"] = "Fit inside the window",
        ["L_LayoutNote"] = "Following the desktop shows the slice the window covers, as if it were see-through. Fitting draws the whole wallpaper inside the window, so moving it changes nothing.",
        ["L_FrameRate"] = "Frame rate",
        ["L_FrameNote"] = "Each frame costs CPU. Capture pauses automatically when the window is minimised or in the background.",
        ["L_TrimNote"] = "Trim edges — with the whole-desktop fallback the icons share the wallpaper surface and trimming keeps them out of shot. The Wallpaper Engine capture is already icon-free.",
        ["L_Left"] = "Left",
        ["L_Right"] = "Right",
        ["L_Top"] = "Top",
        ["L_Bottom"] = "Bottom",

        // ---- settings: backdrop editor ----
        ["L_Browse"] = "Browse",
        ["L_Clear"] = "Clear",
        ["L_Fit"] = "Fit",
        ["L_FitFillCrop"] = "Fill the panel (crop)",
        ["L_FitInside"] = "Fit inside",
        ["L_FitStretch"] = "Stretch to fill",
        ["L_FitOriginal"] = "Original size",
        ["L_PictureBlur"] = "Picture blur",
        ["L_PictureOpacity"] = "Picture opacity",
        ["L_OverlayColour"] = "Overlay colour",
        ["L_OverlayOpacity"] = "Overlay opacity",
        ["L_OverlayBlur"] = "Overlay blur",
        ["L_BackdropWholeWindow"] = "Whole window",
        ["L_BackdropSidebar"] = "Sidebar",
        ["L_BackdropTerminal"] = "Terminal",

        // ---- settings: window ----
        ["L_Window"] = "Window",
        ["L_WindowNote"] = "How the window sits among the others.",
        ["L_AlwaysOnTop"] = "Keep the window above all others",

        // ---- settings: see-through ----
        ["L_SeeThrough"] = "See-through",
        ["L_SeeThroughNote"] = "The window slider fades everything including the desktop behind it. The panel sliders only thin each panel's own colour, letting the background picture show through.",
        ["L_WholeWindow"] = "Whole window",
        ["L_Sidebar"] = "Sidebar",
        ["L_TabBar"] = "Tab bar",
        ["L_Terminal"] = "Terminal",

        // ---- settings: colours ----
        ["L_TerminalColours"] = "Terminal colours",
        ["L_TerminalColoursNote"] = "Accepts #RGB, #RRGGBB, #AARRGGBB or a colour name.",
        ["L_AnsiPalette"] = "ANSI palette",
        ["L_AnsiNote"] = "The sixteen colours programs address by name — ls, git and friends.",
        ["L_Application"] = "Application",
        ["L_ApplicationNote"] = "The window chrome: tab strip, sidebar, dialogs.",
        ["L_InterfaceFont"] = "Interface font",
        ["L_Preview"] = "Preview",
        ["L_PreviewNote"] = "How the palette reads against the terminal background.",

        // ---- settings: colour labels (built in code) ----
        ["L_ColBackground"] = "Background",
        ["L_ColText"] = "Text",
        ["L_ColCursor"] = "Cursor",
        ["L_ColSelection"] = "Selection",
        ["L_AnsiBlack"] = "Black",
        ["L_AnsiBrightBlack"] = "Bright black",
        ["L_AnsiRed"] = "Red",
        ["L_AnsiBrightRed"] = "Bright red",
        ["L_AnsiGreen"] = "Green",
        ["L_AnsiBrightGreen"] = "Bright green",
        ["L_AnsiYellow"] = "Yellow",
        ["L_AnsiBrightYellow"] = "Bright yellow",
        ["L_AnsiBlue"] = "Blue",
        ["L_AnsiBrightBlue"] = "Bright blue",
        ["L_AnsiMagenta"] = "Magenta",
        ["L_AnsiBrightMagenta"] = "Bright magenta",
        ["L_AnsiCyan"] = "Cyan",
        ["L_AnsiBrightCyan"] = "Bright cyan",
        ["L_AnsiWhite"] = "White",
        ["L_AnsiBrightWhite"] = "Bright white",
        ["L_ColAccent"] = "Accent",
        ["L_ColAccentDim"] = "Accent (dim)",
        ["L_ColSurface"] = "Surface",
        ["L_ColSurfaceRaised"] = "Surface (raised)",
        ["L_ColChrome"] = "Chrome",
        ["L_ColChromeHover"] = "Chrome (hover)",
        ["L_ColDivider"] = "Divider",
        ["L_ColTextMuted"] = "Text (muted)",
        ["L_ColTextFaint"] = "Text (faint)",

        // ---- units ----
        ["L_Fps"] = "{0} fps",

        // ---- common buttons ----
        ["L_Cancel"] = "Cancel",
        ["L_Attach"] = "Attach",
        ["L_Refresh"] = "Refresh",
        ["L_Search"] = "Search",
        ["L_LocalModels"] = "Local models",
        ["L_LocalDownloaded"] = "ON THIS MACHINE",
        ["L_LocalStart"] = "Start",
        ["L_LocalUse"] = "Use",
        ["L_LocalGet"] = "Download",
        ["L_LocalPick"] = "Pick a model on the left to see its files.",
        ["L_LocalSearching"] = "Searching…",
        ["L_LocalNothing"] = "Nothing matched that.",
        ["L_LocalNoFiles"] = "no GGUF files in this one",
        ["L_LocalStarting"] = "Starting the model; a large one takes a while to load…",
        ["L_LocalFailed"] = "The download did not finish. Nothing was kept.",
        ["L_LocalDeleteAsk"] = "Delete {0}?",
        ["L_LocalSplitNote"] =
            "This model is published in several parts. Download them from the hub page and put "
            + "them together before using it here — half a model loads as nothing at all.",
        ["L_ChatAsk"] = "Ask the agent…",
        ["L_ChatSend"] = "Send",
        ["L_ChatAttachFile"] = "Attach a file",
        ["L_ChatAttachFolder"] = "Attach a folder",
        ["L_ChatAttachSsh"] = "Attach a saved SSH connection",
        ["L_ChatRemove"] = "Remove",
        ["L_ChatOpenFile"] = "Open file",
        ["L_ChatOpenFolder"] = "Open folder",
        ["L_ChatReveal"] = "Show in Explorer",
        ["L_ChatRun"] = "Run",
        ["L_ChatSkip"] = "Skip",
        ["L_ChatAlways"] = "Always allow",
        ["L_ChatAlwaysNote"] = "“{0}” from now on",
        ["L_ChatAdminWarn"] = "Asks to run as administrator",
        ["L_ChatModelTitle"] = "Model answering this chat",
        ["L_ChatModelOther"] = "Other…",
        ["L_ChatModelPlaceholder"] = "model name",
        ["L_ChatContextTip"] = "Estimated context in use",
        ["L_ChatSpentCounted"] = "Counted by the endpoint",
        ["L_ChatSpentEstimated"] = "Estimated while the reply arrives",
        ["L_ChatCopy"] = "copy",
        ["L_ChatCopied"] = "copied",
        ["L_ChatReasoning"] = "Show what it is working out",
        ["L_ChatStop"] = "Stop",
        ["L_ChatRepeat"] = "Ask again",
        ["L_ChatEdit"] = "Edit and resend",
        ["L_ChatLike"] = "Good answer",
        ["L_ChatDislike"] = "Poor answer",
        ["L_ChatRegenerate"] = "Regenerate",
        ["L_ChatDislikeAsk"] = "What was wrong? (optional — helps train it)",
        ["L_ChatDislikeSend"] = "Send",
        ["L_ChatThink"] = "thought for {0}",
        ["L_ChatDownload"] = "Save the picture",
        ["L_ChatCopyImage"] = "Copy the picture",
        ["L_ChatOpenExternal"] = "Open in the system viewer",
        ["L_ChatClose"] = "Close",
        ["L_ChatPrev"] = "Previous",
        ["L_ChatNext"] = "Next",
        ["L_ChatCmdCompact"] = "compact",
        ["L_ChatCmdCompactHint"] = "Summarise the earlier part of the chat to free the context",
        ["L_ChatCmdRetry"] = "retry",
        ["L_ChatCmdRetryHint"] = "Drop the last answer and ask for another",
        ["L_ChatCtxCopy"] = "Copy",
        ["L_ChatCtxWeb"] = "Search the web",
        ["L_ChatCtxAsk"] = "Ask the agent about this",
        ["L_ChatCtxAskOther"] = "Ask another agent…",
        ["L_ChatQuote"] = "Quote",
        ["L_ChatQuoteMe"] = "You",
        ["L_ChatMentionAll"] = "Everyone",
        ["L_ChatMentionAllTitle"] = "Address everyone again",
        ["L_ChatNoSsh"] = "There are no saved SSH connections to attach.",
        ["L_ChatCompactNothing"] = "There is not enough here to compact yet.",
        ["L_ChatNoOtherAgents"] = "There are no other agents to ask. Add one on the AI page.",
        ["L_ChatAskAboutThis"] = "About this:\n\n{0}",
        ["L_ChatRpAct"] = "Action",
        ["L_ChatRpState"] = "State",
        ["L_ChatRpStatus"] = "Status",
        ["L_ChatRpAttempt"] = "Attempt",
        ["L_ChatRpMe"] = "Me",
        ["L_ChatRpAgent"] = "Agent",
        ["L_ChatRpActPrompt"] = "(Have your character do something in the scene now, and narrate it.)",
        ["L_ChatRpStatePrompt"] = "(Describe your character's current state right now: mood, feelings, "
                                  + "posture, condition.)",
        ["L_ChatRpStatusPrompt"] = "(Show a status block for your character: key traits, condition, "
                                   + "inventory and relationships.)",
        ["L_ChatRpAttemptOk"] = "(Attempt: SUCCESS. Narrate it working out.)",
        ["L_ChatRpAttemptFail"] = "(Attempt: FAILURE. Narrate it going wrong.)",
        ["L_ChatRpStateWord"] = "state: ",
        ["L_ChatRpStatusWord"] = "status: ",
        ["L_ChatRpAttemptWord"] = "attempt: ",
        ["L_ChatRpSuccess"] = "success",
        ["L_ChatRpFail"] = "failure",
        ["L_ChatShowAll"] = "show all {0} lines",
        ["L_ChatOutput"] = "output",
        ["L_PhaseLoading"] = "loading the model — the first time takes a while",
        ["L_PhaseTunnelling"] = "opening the connection to the machine that serves it",
        ["L_TunnelNoSession"] = "This agent is routed through a saved SSH connection that no longer exists.",
        ["L_TunnelNoPort"] =
            "Routing through a connection only works for an address on 127.0.0.1 — that is what "
            + "the tunnel carries. Point the agent at the loopback port the server listens on.",
        ["L_TunnelFailed"] = "The connection to that machine could not be opened: {0}",
        ["L_AiTunnel"] = "Reach it through",
        ["L_AiTunnelNone"] = "Directly, no tunnel",
        ["L_AiTunnelNote"] =
            "For a server that listens only on its own machine. Keep the endpoint pointed at "
            + "127.0.0.1 and that port is carried over this connection while a chat is open — no "
            + "firewall change, no ssh window to keep running.",
        ["L_LocalNotLoaded"] = "The model was registered but the engine is not serving it.",
        ["L_LocalNoFile"] =
            "This model is not loaded and its file is not in the models folder. Download it again "
            + "on the local models page, or start it there.",
        ["L_PhaseThinking"] = "thinking",
        ["L_PhaseDeciding"] = "working out what to do next",
        ["L_PhaseRunning"] = "running a command",
        ["L_PhaseRunningAdmin"] = "running a command as administrator",
        ["L_PhaseReading"] = "reading the output",
        ["L_PhaseWriting"] = "writing the answer",
        ["L_PhaseSharing"] = "sharing a file",
        ["L_PhaseDrawing"] = "drawing a picture",
        ["L_PhaseAsking"] = "asking another agent",
        ["L_PhaseWrappingUp"] = "out of command rounds — writing up what was found",
        ["L_FitGood"] = "runs well",
        ["L_FitTight"] = "tight",
        ["L_FitHeavy"] = "heavy",
        ["L_FitNo"] = "will not run",
        ["L_FitSharedGood"] = "{0} GB leaves most of this machine's {1} GB free.",
        ["L_FitSharedTight"] = "{0} GB takes about half of {1} GB; close other things first.",
        ["L_FitSharedHeavy"] = "{0} GB takes most of {1} GB and will be slow.",
        ["L_FitSharedNo"] = "{0} GB is more than {1} GB of shared memory can hold.",
        ["L_FitCardGood"] = "{0} GB fits in {1} GB of graphics memory.",
        ["L_FitCardTight"] = "{0} GB nearly fills {1} GB of graphics memory; expect little room for a long conversation.",
        ["L_FitCardHeavy"] = "{0} GB is too big for {1} GB of graphics memory, so it would run on the processor — that works, but slowly.",
        ["L_FitCardNo"] = "{0} GB is more than this machine's {1} GB of memory can hold.",
        ["L_MachineCard"] = "{0} GB memory · {1} GB on {2}",
        ["L_MachineShared"] = "{0} GB memory · {1}, sharing that memory",
        ["L_MachineGraphics"] = "graphics",
        ["L_UnitGb"] = "GB",
        ["L_UnitMillions"] = "{0}M",
        ["L_UnitThousands"] = "{0}k",
        ["L_LocalOnlyFits"] = "only what will run",
        ["L_DlDone"] = "{0} of {1} GB",
        ["L_DlSpeed"] = "{0} MB/s",
        ["L_DlLeft"] = "{0} left",
        ["L_WallpaperPaused"] =
            "The live background has stopped because Wallpaper Engine has paused itself. By "
            + "default it pauses while a window is maximised or fullscreen — change that under "
            + "Settings → Performance → “Other applications” in Wallpaper Engine.",
        ["L_CliMissing"] =
            "Claude Code is not installed on this machine. Install it, then sign in with "
            + "“claude /login”, which opens your browser.",
        ["L_CliNoStart"] = "Claude Code could not be started: {0}",
        ["L_CliNoAnswer"] =
            "Claude Code returned nothing. If it has not been signed in yet, run “claude /login” "
            + "in a terminal tab — it opens your browser and keeps the sign-in itself.",
        ["L_CliNotReady"] = "Claude Code is installed but did not answer.",
        ["L_CliNothingToSay"] = "There was nothing to send.",
        ["L_Rename"] = "Rename",
        ["L_LocalInEngine"] = "in the engine's own store",
        ["L_LocalRenameTitle"] = "Name this model",
        ["L_LocalRenameNote"] =
            "Only the label changes. The model, its file and what the engine is asked for stay "
            + "as they are, so existing chats keep working. Leave it empty for the original name.",
        ["L_LocalNoModelLoaded"] = "no model loaded",
        ["L_LocalDownloads"] = "{0:N0} downloads",
        ["L_LocalParts"] = "{0} parts",
        ["L_LocalGone"] = "That model file is no longer there.",
        ["L_LocalNoLlama"] =
            "llama-server was not found. Install the engine on this page, or put llama.cpp's "
            + "llama-server on the PATH.",
        ["L_LocalLlamaFailed"] = "llama-server could not be started: {0}",
        ["L_LocalLlamaQuit"] = "llama-server stopped straight away — the file may not be a model it can read.",
        ["L_LocalLlamaSlow"] = "llama-server did not start answering within a minute.",
        ["L_EngineMissing"] = "Ollama is not installed here yet.",
        ["L_EngineNoAsset"] = "The engine download could not be found.",
        ["L_EngineNoFinish"] = "The engine download did not finish. Nothing was kept.",
        ["L_EngineNoUnpack"] = "The engine could not be unpacked: {0}",
        ["L_EngineNoExe"] = "The download unpacked, but ollama.exe was not in it.",
        ["L_ImageEngineNoExe"] = "The download unpacked, but the image engine (sd-cli.exe) was not in it.",
        ["L_EngineNoStart"] = "Ollama could not be started: {0}",
        ["L_EngineQuit"] = "Ollama stopped straight away — something else may be using its port.",
        ["L_EngineSlow"] = "Ollama did not start answering.",
        ["L_EngineNoRun"] = "Ollama could not be run.",
        ["L_EngineListing"] = "The release listing could not be read: {0}",
        ["L_LocalEngineInstall"] = "Install engine",
        ["L_LocalEngineStart"] = "Start engine",
        ["L_LocalEngineStop"] = "Stop engine",
        ["L_LocalEngineStarting"] = "Starting the engine…",
        ["L_LocalEngineFetching"] = "Downloading the engine. This is a large file; it can be left running.",
        ["L_LocalEngineIdle"] = "The engine is installed but not running. Start it to load a model.",
        ["L_LocalEngineAsk"] =
            "Download Ollama and unpack it into\n\n{0}\n\nIt is about 1.4 GB and needs no "
            + "administrator rights. Models downloaded here are kept beside it, so the whole "
            + "folder stays portable.",
        ["L_LocalNoRunner"] =
            "No local engine is installed. “Install engine” fetches Ollama into the app's own "
            + "folder; an Ollama or llama-server you installed yourself is picked up as it is.",
        ["L_AiAttachSsh"] = "Attach an SSH connection",
        ["L_AiAttachSshNote"] =
            "The agent is given the host, port, account and tunnels so it can write commands "
            + "for this machine, and is told that the work is meant to happen there.",
        ["L_AiSshSendSecret"] = "Send the saved password too",
        ["L_AiSshSendSecretNote"] =
            "The password becomes part of the message and reaches whatever endpoint this agent "
            + "uses, in the clear, and stays in that endpoint's logs. Turn it on only for an "
            + "endpoint you trust with it.",
        ["L_AiSshSecretSent"] = "password sent",
        ["L_Save"] = "Save",
        ["L_Connect"] = "Connect",
        ["L_Remove"] = "Remove",

        // ---- session dialog ----
        ["L_NewSshSessionHeader"] = "New SSH session",
        ["L_EditSshSessionHeader"] = "Edit SSH session",
        ["L_PasteSshTip"] = "Fill this in from an ssh command on the clipboard",
        ["L_FieldName"] = "NAME",
        ["L_FieldHost"] = "HOST",
        ["L_FieldPort"] = "PORT",
        ["L_FieldUsername"] = "USERNAME",
        ["L_FieldAuth"] = "AUTHENTICATION",
        ["L_AuthPassword"] = "Password",
        ["L_AuthPrivateKey"] = "Private key",
        ["L_FieldPassword"] = "PASSWORD",
        ["L_PasswordDpapiNote"] = "Stored encrypted with Windows DPAPI under your account. Leave empty to be asked on each connect.",
        ["L_FieldKeyFile"] = "PRIVATE KEY FILE",
        ["L_FieldPassphrase"] = "PASSPHRASE",
        ["L_FieldTunnels"] = "TUNNELS",
        ["L_AddTunnelTip"] = "Add a tunnel",
        ["L_TunnelLocalPortTip"] = "Local port to listen on",
        ["L_TunnelDestHostTip"] = "Destination host, as the far end sees it",
        ["L_TunnelDestPortTip"] = "Destination port",
        ["L_FieldConnection"] = "CONNECTION",
        ["L_AutoReconnect"] = "Reconnect automatically if the connection drops",
        ["L_AutoReconnectNote"] = "Retries with a growing delay, up to five times. A session that stays up for a minute resets the count.",
        ["L_ErrClipboardRead"] = "Could not read the clipboard.",
        ["L_ErrClipboardEmpty"] = "The clipboard is empty. Copy an ssh command first.",
        ["L_ErrNotSshCommand"] = "That does not look like an ssh command.",
        ["L_ErrHostRequired"] = "Host is required.",
        ["L_ErrUserRequired"] = "Username is required.",
        ["L_ErrPortRange"] = "Port must be between 1 and 65535.",
        ["L_ErrChooseKey"] = "Choose a private key file.",
        ["L_ErrKeyMissing"] = "That private key file does not exist.",
        ["L_ErrTunnelIncomplete"] = "A tunnel is incomplete.",
        ["L_ErrTunnelDuplicate"] = "Two tunnels both listen on {0}.",

        // ---- password prompt ----
        ["L_PasswordRequired"] = "Password required",

        // ---- host key prompt ----
        ["L_PresentedFingerprint"] = "PRESENTED FINGERPRINT",
        ["L_PreviouslyTrusted"] = "PREVIOUSLY TRUSTED FINGERPRINT",
        ["L_ConnectOnce"] = "Connect once",
        ["L_TrustRemember"] = "Trust and remember",
        ["L_ReplaceStoredKey"] = "Replace stored key",
        ["L_CancelConnection"] = "Cancel connection",
        ["L_HkUnknownServer"] = "Unknown server",
        ["L_HkNewKeyType"] = "New key type for a known host",
        ["L_HkChanged"] = "Host key has changed",
        ["L_HkAlgoBits"] = "{0} · {1} bit",
        ["L_HkFirstBody"] = "RedBloom has not connected to {0} before, so it cannot tell whether this is the right machine. Check the fingerprint against the server before trusting it.",
        ["L_HkFirstHint"] = "On the server, `ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub` prints the fingerprint it should be showing.",
        ["L_HkNewAlgoBody"] = "{0} is already trusted, but has never presented a key of this type before. That is normal after a server reconfiguration — and is also what an interception attempt would look like. Verify the fingerprint.",
        ["L_HkNewAlgoHint"] = "If you did not change anything on the server, do not trust this key.",
        ["L_HkChangedBody"] = "The key presented by {0} does not match the one RedBloom trusted previously. This happens when a server is rebuilt or its keys are rotated — but it is also exactly what a machine-in-the-middle attack looks like. Do not continue unless you know why the key changed.",
        ["L_HkChangedHint"] = "Anything you type — including passwords — would go to whoever holds this key.",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>
    {
        ["L_CloseTabTip"] = "Закрыть вкладку (Ctrl+Shift+W)",
        ["L_Edit"] = "Изменить",
        ["L_Delete"] = "Удалить",
        ["L_CollapseSidebarTip"] = "Свернуть боковую панель (Ctrl+Shift+B)",
        ["L_NewTabTip"] = "Новая вкладка (Ctrl+Shift+T)",
        ["L_ChooseShell"] = "Выбрать оболочку",
        ["L_TabCard"] = "Карточка вкладки",
        ["L_CardColor"] = "Цвет",
        ["L_CardOpacity"] = "Непрозрачность",
        ["L_CardBlur"] = "Блюр",
        ["L_CardImage"] = "Картинка",
        ["L_CardIcon"] = "Значок (глиф Segoe)",
        ["L_CardReset"] = "Сбросить",
        ["L_CardRightClickHint"] = "ПКМ по вкладке — цвет, прозрачность и блюр.",
        ["L_SplitSameTip"] = "Сплит: ещё один шелл на этом SSH-подключении (Ctrl+Alt+D)",
        ["L_SplitNewTip"] = "Сплит: новая сессия рядом (Ctrl+Shift+D)",
        ["L_CloseSplitTip"] = "Закрыть этот сплит (Ctrl+Alt+A)",
        ["L_Minimize"] = "Свернуть",
        ["L_Maximize"] = "Развернуть",
        ["L_Close"] = "Закрыть",
        ["L_MinimizeToTray"] = "Свернуть в трей",
        ["L_TrayShow"] = "Показать RedBloom",
        ["L_TrayExit"] = "Выход",
        ["L_RestartAdmin"] = "Перезапустить от администратора",
        ["L_ElevateNow"] = "Получить права администратора",
        ["L_ElevateReady"] = "Права администратора получены. Команды, которым они нужны, теперь выполняются с ними.",
        ["L_AlreadyAdmin"] = "Запущено от администратора",
        ["L_SshSessions"] = "SSH-СЕССИИ",
        ["L_NewSshSession"] = "Новая SSH-сессия",
        ["L_SaveThisSession"] = "Сохранить это подключение в боковую панель?",
        ["L_SaveToastSaved"] = "Сохранено «{0}».",
        ["L_Dismiss"] = "Скрыть",
        ["L_FilterHint"] = "Фильтр…",
        ["L_NoSavedSessions"] = "Нет сохранённых сессий",
        ["L_UsePlusToAdd"] = "Нажмите + выше, чтобы добавить",
        ["L_NoOpenTerminals"] = "Нет открытых терминалов",
        ["L_EmptyHint"] = "Ctrl+Shift+T — новая вкладка  ·  двойной клик по сессии для подключения",
        ["L_Settings"] = "Параметры",
        ["L_AiSettings"] = "Параметры AI",

        // ---- AI agents ----
        ["L_AiTitle"] = "AI-агенты",
        ["L_AiNote"] = "Агент — это эндпоинт, модель и постоянные инструкции. "
                       + "Запущенный агент открывается вкладкой, как оболочка или SSH-сессия.",
        ["L_AiAdd"] = "Добавить",
        ["L_AiDelete"] = "Удалить",
        ["L_AiNewAgent"] = "Новый агент",
        ["L_AiName"] = "Название",
        ["L_AiProvider"] = "API",
        ["L_AiOpenAiCompatible"] = "OpenAI-совместимый",
        ["L_AiClaudeCli"] = "Claude Code (CLI)",
        ["L_AiClaudeCliNote"] = "Использует установленный Claude Code из командной строки. Он входит "
                               + "сам и сам выбирает модель — поэтому эндпоинт, ключ и модель задавать не нужно.",
        ["L_AiAddLocal"] = "＋ Локальная модель",
        ["L_AiAddLocalNone"] = "Локальные модели на этой машине не найдены",
        ["L_AiAddLocalAll"] = "Все локальные модели уже добавлены",
        ["L_AiLocalModelNote"] = "Модель на этой машине ({0}). Движок запускается при первом "
                                + "сообщении; эндпоинт и ключ задавать не нужно.",
        ["L_AiBaseUrl"] = "Эндпоинт",
        ["L_AiBaseUrlNote"] = "Пусто — собственный адрес провайдера. Запросы уходят на {0}.",
        ["L_AiApiKey"] = "Ключ API",
        ["L_AiModel"] = "Модель",
        ["L_AiAvatar"] = "Аватар",
        ["L_AiNameColor"] = "Цвет ника",
        ["L_AiMaxTokens"] = "Предел ответа (токены)",
        ["L_AiContextWindow"] = "Окно контекста (токены)",
        ["L_AiContextWindowNote"] = "Сколько модель держит за раз. От этого зависит шкала под чатом "
                                    + "и момент, когда ранняя часть переписки сворачивается в конспект.",
        ["L_AiEffort"] = "Усилие",
        ["L_AiThinking"] = "Разрешить модели подумать",
        ["L_AiThinkingNote"] = "Адаптивно: модель сама решает, сколько размышлений стоит вопрос. "
                               + "Сами рассуждения наружу не отдаются, поэтому такой ход выглядит как пауза.",
        ["L_AiAllowCommands"] = "Разрешить агенту выполнять команды",
        ["L_AiAllowCommandsNote"] = "Агент получает инструмент, запускающий команды на этой машине — "
                                    + "с правами твоей учётки. На то, что он решит запустить, влияет "
                                    + "всё прочитанное по дороге, поэтому подтверждение лучше не "
                                    + "выключать, если не смотришь за сессией.",
        ["L_AiAskBeforeRun"] = "Спрашивать перед каждой командой",
        ["L_AiAllowAgents"] = "Разрешить агенту звать других агентов",
        ["L_AiAllowAgentsNote"] = "Агент получает инструмент, который передаёт запрос другому твоему агенту "
                                  + "по имени и получает результат — особенно полезно с image-агентом, "
                                  + "который рисует картинку. Вызванный агент работает сам, без инструментов, "
                                  + "поэтому вызовы не идут по цепочке.",
        ["L_AiAllowImages"] = "Разрешить агенту рисовать картинки",
        ["L_AiAllowImagesNote"] = "Агент получает инструмент, который рисует картинку по описанию "
                                  + "локальной image-моделью (stable-diffusion.cpp) и показывает её в чате. "
                                  + "Нужен установленный движок картинок и diffusion-.gguf в папке AIModels.",
        ["L_AiImageEngineInstall"] = "Установить движок картинок",
        ["L_AiImageEngineReinstall"] = "Переустановить (сменить бэкенд)",
        ["L_AiImageEngineReady"] = "Движок картинок установлен.",
        ["L_AiImageEngineInstalledFmt"] = "Установлен: {0}.",
        ["L_AiImageEngineSuggest"] = "Не установлен. Рекомендуется для твоего железа: {0}.",
        ["L_AiImageEngineInstalling"] = "Скачиваю… {0}%",
        ["L_AiImageEngineAsk"] = "Скачать сборку {0} для stable-diffusion.cpp в {1}? Это несколько сотен "
                                 + "мегабайт, ставится рядом с программой, без прав администратора.",
        ["L_AiPickModel"] = "Выбрать…",
        ["L_AiPickModelNone"] = "Локальных моделей не найдено",
        ["L_AiImageModel"] = "Локальная модель картинок",
        ["L_AiImageModelNote"] = "Какой diffusion-моделью рисовать. Найдено: {0}. Пусто — первая из списка.",
        ["L_AiImageModelNoneNote"] = "В папке AIModels нет diffusion-модели. Положи туда diffusion-.gguf.",
        ["L_ImageAgentNoPrompt"] = "Напиши, что нарисовать, — модель нарисует.",
        ["L_ImageAgentNoEngine"] = "Движок картинок не установлен. Поставь его под «Разрешить агенту рисовать картинки».",
        ["L_ImageAgentNoModel"] = "Для этого агента не найдена diffusion-модель.",
        ["L_AiAllowedCommands"] = "Разрешено без вопросов",
        ["L_AiAllowedCommandsNote"] = "По строке на образец. Строка подходит команде, равной ей или "
                                      + "начинающейся с неё и пробела: «git» покрывает любой вызов git, "
                                      + "«git status» — только его. Ответ [a] в приглашении добавляет "
                                      + "строку сюда.",
        ["L_AiSystemPrompt"] = "Постоянные инструкции",
        ["L_AiRoleplay"] = "РП-модель (играет персонажа)",
        ["L_AiRoleplayNote"] = "Карточка персонажа ниже уходит впереди всего остального, поэтому модель "
                               + "отвечает от лица персонажа, а не называет того, кто её обучал. Пустые "
                               + "поля не отправляются.",
        ["L_CharCard"] = "Карточка персонажа",
        ["L_CharName"] = "Имя",
        ["L_CharSex"] = "Пол",
        ["L_CharAge"] = "Возраст",
        ["L_CharRace"] = "Раса",
        ["L_CharHeight"] = "Рост",
        ["L_CharWeight"] = "Вес",
        ["L_CharHair"] = "Волосы",
        ["L_CharSkin"] = "Кожа",
        ["L_CharManner"] = "Манера речи",
        ["L_CharLikes"] = "Нравится",
        ["L_CharDislikes"] = "Не нравится",
        ["L_CharHobbies"] = "Хобби",
        ["L_CharBiography"] = "Биография",
        ["L_CharScenario"] = "Сцена",
        ["L_CharGreeting"] = "Приветствие",
        ["L_CharOther"] = "Ещё",
        ["L_AiTest"] = "Проверить связь",
        ["L_AiTesting"] = "Проверяю…",
        ["L_AiTestOk"] = "Эндпоинт ответил, ключ принят.",
        ["L_AiTestFailed"] = "Не вышло: {0}",
        ["L_AiLaunch"] = "Запустить",
        ["L_AiImport"] = "Импорт",
        ["L_AiImportTitle"] = "Импорт конфига",
        ["L_AiImportNote"] = "Вставь настройки консольного Claude-инструмента — объект с блоком "
                             + "\"env\". На каждую названную модель заводится агент.",
        ["L_AiImportFromFile"] = "Из файла…",
        ["L_AiImportAction"] = "Импортировать",
        ["L_AiImportReading"] = "Читаю конфиг…",
        ["L_AiImported"] = "Импортировано: {0}.",
        ["L_AiChats"] = "ЧАТЫ",
        ["L_AiNewChat"] = "Новый чат",
        ["L_RoomsTab"] = "Комнаты",
        ["L_RoomNone"] = "Пока нет комнат. Создай кнопкой + сверху.",
        ["L_RoomNew"] = "Новая комната",
        ["L_RoomTitle"] = "Комната",
        ["L_RoomName"] = "Название",
        ["L_RoomParticipants"] = "Участники",
        ["L_RoomAvatarNone"] = "нет картинки",
        ["L_RoomKindImage"] = "картинки",
        ["L_RoomKindLocal"] = "локальная",
        ["L_RoomMode"] = "Кто отвечает",
        ["L_RoomModerator"] = "Модератор",
        ["L_RoomOpen"] = "Открыть",
        ["L_RoomEdit"] = "Настроить комнату",
        ["L_RoomEmpty"] = "В комнате нет участников. Добавь их в настройках комнаты.",
        ["L_RoomNeedAgents"] = "Добавь в комнату хотя бы одного агента. Сначала настрой агентов на вкладке ИИ.",
        ["L_RoomUser"] = "Пользователь",
        ["L_RoomPolicyMention"] = "По @упоминанию",
        ["L_RoomPolicyRoundRobin"] = "По очереди",
        ["L_RoomPolicyAll"] = "Все",
        ["L_RoomPolicyModerator"] = "Решает модератор",
        ["L_RoomPolicyMentionNote"] = "Никто не отвечает, пока его не назовут через @ — ты или другой агент. "
                                      + "Самая тихая комната; ведёшь её ты.",
        ["L_RoomPolicyRoundRobinNote"] = "На каждое сообщение отвечает один агент, по кругу в порядке списка.",
        ["L_RoomPolicyAllNote"] = "На каждое сообщение отвечают все агенты, в порядке списка.",
        ["L_RoomPolicyModeratorNote"] = "Агент-модератор решает, кто говорит следующим, пока не сочтёт "
                                        + "разговор законченным.",
        ["L_AiNoChats"] = "С этим агентом ещё нет чатов",
        ["L_AiDeleteChat"] = "Удалить чат",
        ["L_AiChatName"] = "Название чата",
        ["L_AiChatNameNote"] = "Пусто — снова назвать по первому вопросу.",
        ["L_AiRenameChat"] = "Переименовать чат (F2)",
        ["L_AiBotName"] = "Имя агента в этом чате",
        ["L_AiBotNameNote"] = "Пусто — берётся имя агента.",
        ["L_AiChatAvatar"] = "Аватар этого чата",
        ["L_AiChatAvatarNote"] = "Пусто — берётся картинка агента.",

        ["L_Appearance"] = "Внешний вид",
        ["L_AppearanceNote"] = "Изменения применяются сразу и сохраняются на ходу.",
        ["L_ResetDefaults"] = "Сбросить по умолчанию",

        ["L_Language"] = "Язык",
        ["L_LanguageNote"] = "Язык интерфейса. Применяется мгновенно.",

        ["L_Integration"] = "Интеграция",
        ["L_IntegrationNote"] = "Добавить RedBloom в Проводник, чтобы открывать шелл в любой папке. Стать терминалом Windows по умолчанию требует более глубокой интеграции с ОС и здесь не предлагается.",
        ["L_OpenHere"] = "Открыть RedBloom здесь",
        ["L_OpenHereToggle"] = "Показывать «Открыть RedBloom здесь» в контекстном меню папок",

        ["L_TerminalText"] = "Текст терминала",
        ["L_TerminalTextNote"] = "Показаны только моноширинные шрифты — пропорциональный сломал бы выравнивание столбцов.",
        ["L_Font"] = "Шрифт",
        ["L_Size"] = "Размер",
        ["L_LineHeight"] = "Высота строки",
        ["L_Cursor"] = "Курсор",
        ["L_CursorBar"] = "Черта",
        ["L_CursorBlock"] = "Блок",
        ["L_CursorUnderline"] = "Подчёркивание",
        ["L_Blink"] = "Мигание",
        ["L_Scrollback"] = "Буфер прокрутки",

        ["L_BackgroundPicture"] = "Фоновое изображение",
        ["L_BackgroundPictureNote"] = "Одна картинка за всем окном или отдельная для каждой панели.",
        ["L_BgNone"] = "Нет",
        ["L_BgWindow"] = "Всё окно",
        ["L_BgRegions"] = "По панелям",
        ["L_BgLive"] = "Живые обои",
        ["L_LiveNote"] = "Показывает сами обои рабочего стола, вместе с анимацией — сцены Wallpaper Engine работают. Блюр, наложение и прозрачность ниже всё равно применяются.",
        ["L_Layout"] = "Отображение",
        ["L_FollowDesktop"] = "Следовать за рабочим столом",
        ["L_FitInsideWindow"] = "Вписать в окно",
        ["L_LayoutNote"] = "«Следовать за рабочим столом» показывает область под окном, будто оно прозрачное. «Вписать» рисует все обои внутри окна, поэтому перемещение ничего не меняет.",
        ["L_FrameRate"] = "Частота кадров",
        ["L_FrameNote"] = "Каждый кадр тратит процессор. Захват сам встаёт на паузу, когда окно свёрнуто или в фоне.",
        ["L_TrimNote"] = "Обрезка краёв — в запасном режиме захвата всего рабочего стола иконки лежат на тех же обоях, и обрезка убирает их из кадра. Захват из Wallpaper Engine уже без иконок.",
        ["L_Left"] = "Слева",
        ["L_Right"] = "Справа",
        ["L_Top"] = "Сверху",
        ["L_Bottom"] = "Снизу",

        ["L_Browse"] = "Обзор",
        ["L_Clear"] = "Очистить",
        ["L_Fit"] = "Вписывание",
        ["L_FitFillCrop"] = "Заполнить панель (обрезка)",
        ["L_FitInside"] = "Вписать целиком",
        ["L_FitStretch"] = "Растянуть на всю",
        ["L_FitOriginal"] = "Исходный размер",
        ["L_PictureBlur"] = "Блюр картинки",
        ["L_PictureOpacity"] = "Непрозрачность картинки",
        ["L_OverlayColour"] = "Цвет наложения",
        ["L_OverlayOpacity"] = "Непрозрачность наложения",
        ["L_OverlayBlur"] = "Блюр наложения",
        ["L_BackdropWholeWindow"] = "Всё окно",
        ["L_BackdropSidebar"] = "Боковая панель",
        ["L_BackdropTerminal"] = "Терминал",

        ["L_Window"] = "Окно",
        ["L_WindowNote"] = "Как окно ведёт себя среди других.",
        ["L_AlwaysOnTop"] = "Держать окно поверх всех остальных",

        ["L_SeeThrough"] = "Прозрачность",
        ["L_SeeThroughNote"] = "Ползунок окна гасит всё, включая рабочий стол за ним. Ползунки панелей лишь разбавляют собственный цвет панели, пропуская фоновую картинку.",
        ["L_WholeWindow"] = "Всё окно",
        ["L_Sidebar"] = "Боковая панель",
        ["L_TabBar"] = "Панель вкладок",
        ["L_Terminal"] = "Терминал",

        ["L_TerminalColours"] = "Цвета терминала",
        ["L_TerminalColoursNote"] = "Принимает #RGB, #RRGGBB, #AARRGGBB или имя цвета.",
        ["L_AnsiPalette"] = "Палитра ANSI",
        ["L_AnsiNote"] = "Шестнадцать цветов, к которым программы обращаются по имени — ls, git и прочие.",
        ["L_Application"] = "Приложение",
        ["L_ApplicationNote"] = "Оформление окна: вкладки, боковая панель, диалоги.",
        ["L_InterfaceFont"] = "Шрифт интерфейса",
        ["L_Preview"] = "Предпросмотр",
        ["L_PreviewNote"] = "Как палитра читается на фоне терминала.",

        ["L_ColBackground"] = "Фон",
        ["L_ColText"] = "Текст",
        ["L_ColCursor"] = "Курсор",
        ["L_ColSelection"] = "Выделение",
        ["L_AnsiBlack"] = "Чёрный",
        ["L_AnsiBrightBlack"] = "Ярко-чёрный",
        ["L_AnsiRed"] = "Красный",
        ["L_AnsiBrightRed"] = "Ярко-красный",
        ["L_AnsiGreen"] = "Зелёный",
        ["L_AnsiBrightGreen"] = "Ярко-зелёный",
        ["L_AnsiYellow"] = "Жёлтый",
        ["L_AnsiBrightYellow"] = "Ярко-жёлтый",
        ["L_AnsiBlue"] = "Синий",
        ["L_AnsiBrightBlue"] = "Ярко-синий",
        ["L_AnsiMagenta"] = "Пурпурный",
        ["L_AnsiBrightMagenta"] = "Ярко-пурпурный",
        ["L_AnsiCyan"] = "Бирюзовый",
        ["L_AnsiBrightCyan"] = "Ярко-бирюзовый",
        ["L_AnsiWhite"] = "Белый",
        ["L_AnsiBrightWhite"] = "Ярко-белый",
        ["L_ColAccent"] = "Акцент",
        ["L_ColAccentDim"] = "Акцент (тусклый)",
        ["L_ColSurface"] = "Поверхность",
        ["L_ColSurfaceRaised"] = "Поверхность (приподнятая)",
        ["L_ColChrome"] = "Оформление",
        ["L_ColChromeHover"] = "Оформление (наведение)",
        ["L_ColDivider"] = "Разделитель",
        ["L_ColTextMuted"] = "Текст (приглушённый)",
        ["L_ColTextFaint"] = "Текст (бледный)",

        ["L_Fps"] = "{0} к/с",

        ["L_Cancel"] = "Отмена",
        ["L_Attach"] = "Прикрепить",
        ["L_Refresh"] = "Обновить",
        ["L_Search"] = "Искать",
        ["L_LocalModels"] = "Локальные модели",
        ["L_LocalDownloaded"] = "НА ЭТОЙ МАШИНЕ",
        ["L_LocalStart"] = "Запустить",
        ["L_LocalUse"] = "Использовать",
        ["L_LocalGet"] = "Скачать",
        ["L_LocalPick"] = "Выберите модель слева, чтобы увидеть её файлы.",
        ["L_LocalSearching"] = "Ищу…",
        ["L_LocalNothing"] = "Ничего не нашлось.",
        ["L_LocalNoFiles"] = "нет файлов GGUF",
        ["L_LocalStarting"] = "Запускаю модель; крупная грузится не сразу…",
        ["L_LocalFailed"] = "Загрузка не завершилась. Ничего не сохранено.",
        ["L_LocalDeleteAsk"] = "Удалить {0}?",
        ["L_LocalSplitNote"] =
            "Эта модель выложена частями. Скачайте их со страницы модели и соберите перед "
            + "использованием — половина модели не загрузится вовсе.",
        ["L_ChatAsk"] = "Спросите агента…",
        ["L_ChatSend"] = "Отправить",
        ["L_ChatAttachFile"] = "Прикрепить файл",
        ["L_ChatAttachFolder"] = "Прикрепить папку",
        ["L_ChatAttachSsh"] = "Прикрепить сохранённое SSH-подключение",
        ["L_ChatRemove"] = "Убрать",
        ["L_ChatOpenFile"] = "Открыть файл",
        ["L_ChatOpenFolder"] = "Открыть папку",
        ["L_ChatReveal"] = "Показать в проводнике",
        ["L_ChatRun"] = "Выполнить",
        ["L_ChatSkip"] = "Пропустить",
        ["L_ChatAlways"] = "Разрешить всегда",
        ["L_ChatAlwaysNote"] = "«{0}» — впредь без вопросов",
        ["L_ChatAdminWarn"] = "Просит права администратора",
        ["L_ChatModelTitle"] = "Модель, отвечающая в этом чате",
        ["L_ChatModelOther"] = "Другая…",
        ["L_ChatModelPlaceholder"] = "имя модели",
        ["L_ChatContextTip"] = "Примерная занятость контекста",
        ["L_ChatSpentCounted"] = "Посчитано эндпоинтом",
        ["L_ChatSpentEstimated"] = "Оценка, пока идёт ответ",
        ["L_ChatCopy"] = "копировать",
        ["L_ChatCopied"] = "скопировано",
        ["L_ChatReasoning"] = "Показать ход мысли",
        ["L_ChatStop"] = "Остановить",
        ["L_ChatRepeat"] = "Спросить снова",
        ["L_ChatEdit"] = "Изменить и отправить",
        ["L_ChatLike"] = "Хороший ответ",
        ["L_ChatDislike"] = "Плохой ответ",
        ["L_ChatRegenerate"] = "Перегенерировать",
        ["L_ChatDislikeAsk"] = "Что не так? (необязательно — поможет обучить)",
        ["L_ChatDislikeSend"] = "Отправить",
        ["L_ChatThink"] = "думал {0}",
        ["L_ChatDownload"] = "Сохранить картинку",
        ["L_ChatCopyImage"] = "Копировать картинку",
        ["L_ChatOpenExternal"] = "Открыть в системном просмотрщике",
        ["L_ChatClose"] = "Закрыть",
        ["L_ChatPrev"] = "Назад",
        ["L_ChatNext"] = "Вперёд",
        ["L_ChatCmdCompact"] = "compact",
        ["L_ChatCmdCompactHint"] = "Сжать раннюю часть чата, чтобы освободить контекст",
        ["L_ChatCmdRetry"] = "retry",
        ["L_ChatCmdRetryHint"] = "Убрать последний ответ и запросить другой",
        ["L_ChatCtxCopy"] = "Копировать",
        ["L_ChatCtxWeb"] = "Найти в интернете",
        ["L_ChatCtxAsk"] = "Спросить у агента",
        ["L_ChatCtxAskOther"] = "Спросить у другого агента…",
        ["L_ChatQuote"] = "Цитировать",
        ["L_ChatQuoteMe"] = "Вы",
        ["L_ChatMentionAll"] = "Все",
        ["L_ChatMentionAllTitle"] = "Снова обращаться ко всем",
        ["L_ChatNoSsh"] = "Нет сохранённых SSH-подключений для прикрепления.",
        ["L_ChatCompactNothing"] = "Пока что сжимать особо нечего.",
        ["L_ChatNoOtherAgents"] = "Нет других агентов, чтобы спросить. Добавь агента на вкладке ИИ.",
        ["L_ChatAskAboutThis"] = "Про это:\n\n{0}",
        ["L_ChatRpAct"] = "Действие",
        ["L_ChatRpState"] = "Состояние",
        ["L_ChatRpStatus"] = "Статус",
        ["L_ChatRpAttempt"] = "Попытка",
        ["L_ChatRpMe"] = "Я",
        ["L_ChatRpAgent"] = "Агент",
        ["L_ChatRpActPrompt"] = "(Пусть твой персонаж сейчас что-то сделает в сцене, и опиши это.)",
        ["L_ChatRpStatePrompt"] = "(Опиши текущее состояние твоего персонажа прямо сейчас: настроение, "
                                  + "чувства, поза, самочувствие.)",
        ["L_ChatRpStatusPrompt"] = "(Покажи статус персонажа: ключевые характеристики, состояние, "
                                   + "инвентарь и отношения.)",
        ["L_ChatRpAttemptOk"] = "(Попытка: УСПЕХ. Опиши, как всё получилось.)",
        ["L_ChatRpAttemptFail"] = "(Попытка: ПРОВАЛ. Опиши, как всё пошло не так.)",
        ["L_ChatRpStateWord"] = "состояние: ",
        ["L_ChatRpStatusWord"] = "статус: ",
        ["L_ChatRpAttemptWord"] = "попытка: ",
        ["L_ChatRpSuccess"] = "успех",
        ["L_ChatRpFail"] = "провал",
        ["L_ChatShowAll"] = "показать все строки: {0}",
        ["L_ChatOutput"] = "вывод",
        ["L_PhaseLoading"] = "загружаю модель — в первый раз это небыстро",
        ["L_PhaseTunnelling"] = "открываю соединение с машиной, где она работает",
        ["L_TunnelNoSession"] = "Агент направлен через сохранённое SSH-подключение, которого больше нет.",
        ["L_TunnelNoPort"] =
            "Через подключение можно вести только адрес на 127.0.0.1 — именно этот порт и "
            + "переносится. Укажите агенту локальный порт, который слушает сервер.",
        ["L_TunnelFailed"] = "Не удалось открыть соединение с той машиной: {0}",
        ["L_AiTunnel"] = "Идти через",
        ["L_AiTunnelNone"] = "Напрямую, без туннеля",
        ["L_AiTunnelNote"] =
            "Для сервера, который слушает только на своей машине. Оставьте адрес на 127.0.0.1 — "
            + "этот порт будет перенесён через выбранное подключение, пока открыт чат. Ни правок "
            + "файрвола, ни отдельного окна с ssh.",
        ["L_LocalNotLoaded"] = "Модель зарегистрирована, но движок её не отдаёт.",
        ["L_LocalNoFile"] =
            "Модель не загружена, и её файла нет в папке моделей. Скачайте заново на странице "
            + "локальных моделей или запустите её оттуда.",
        ["L_PhaseThinking"] = "думаю",
        ["L_PhaseDeciding"] = "решаю, что делать дальше",
        ["L_PhaseRunning"] = "выполняю команду",
        ["L_PhaseRunningAdmin"] = "выполняю команду от администратора",
        ["L_PhaseReading"] = "читаю вывод",
        ["L_PhaseWriting"] = "пишу ответ",
        ["L_PhaseSharing"] = "передаю файл",
        ["L_PhaseDrawing"] = "рисую картинку",
        ["L_PhaseAsking"] = "спрашиваю другого агента",
        ["L_PhaseWrappingUp"] = "команды кончились — подвожу итог",
        ["L_FitGood"] = "потянет",
        ["L_FitTight"] = "впритык",
        ["L_FitHeavy"] = "тяжело",
        ["L_FitNo"] = "не потянет",
        ["L_FitSharedGood"] = "{0} ГБ оставляют большую часть из {1} ГБ свободной.",
        ["L_FitSharedTight"] = "{0} ГБ — это около половины из {1} ГБ; закройте лишнее.",
        ["L_FitSharedHeavy"] = "{0} ГБ займут почти все {1} ГБ, и работать будет медленно.",
        ["L_FitSharedNo"] = "{0} ГБ больше, чем вмещают {1} ГБ общей памяти.",
        ["L_FitCardGood"] = "{0} ГБ помещаются в {1} ГБ видеопамяти.",
        ["L_FitCardTight"] = "{0} ГБ почти заполняют {1} ГБ видеопамяти; на длинный разговор места останется мало.",
        ["L_FitCardHeavy"] = "{0} ГБ не влезают в {1} ГБ видеопамяти, поэтому считать будет процессор — это работает, но медленно.",
        ["L_FitCardNo"] = "{0} ГБ больше, чем вмещают {1} ГБ памяти этой машины.",
        ["L_MachineCard"] = "{0} ГБ памяти · {1} ГБ у {2}",
        ["L_MachineShared"] = "{0} ГБ памяти · {1}, память общая",
        ["L_MachineGraphics"] = "видеоядро",
        ["L_UnitGb"] = "ГБ",
        ["L_UnitMillions"] = "{0} млн",
        ["L_UnitThousands"] = "{0} тыс.",
        ["L_LocalOnlyFits"] = "только те, что потянет",
        ["L_DlDone"] = "{0} из {1} ГБ",
        ["L_DlSpeed"] = "{0} МБ/с",
        ["L_DlLeft"] = "осталось {0}",
        ["L_WallpaperPaused"] =
            "Живой фон замер: Wallpaper Engine поставил себя на паузу. По умолчанию он делает "
            + "это, пока какое-то окно развёрнуто или на весь экран — поменять можно в его "
            + "настройках: «Производительность» → «Другие приложения».",
        ["L_CliMissing"] =
            "Claude Code на этой машине не установлен. Поставьте его и войдите командой "
            + "«claude /login» — она откроет браузер.",
        ["L_CliNoStart"] = "Не удалось запустить Claude Code: {0}",
        ["L_CliNoAnswer"] =
            "Claude Code ничего не вернул. Если вход ещё не выполнен, выполните «claude /login» "
            + "во вкладке терминала — команда откроет браузер и сохранит вход у себя.",
        ["L_CliNotReady"] = "Claude Code установлен, но не ответил.",
        ["L_CliNothingToSay"] = "Отправлять было нечего.",
        ["L_Rename"] = "Переименовать",
        ["L_LocalInEngine"] = "в хранилище движка",
        ["L_LocalRenameTitle"] = "Название модели",
        ["L_LocalRenameNote"] =
            "Меняется только подпись. Сама модель, её файл и то, что запрашивается у движка, "
            + "остаются прежними — существующие чаты продолжат работать. Пусто — вернуть исходное.",
        ["L_LocalNoModelLoaded"] = "модель не загружена",
        ["L_LocalDownloads"] = "{0:N0} скачиваний",
        ["L_LocalParts"] = "частей: {0}",
        ["L_LocalGone"] = "Этого файла модели больше нет.",
        ["L_LocalNoLlama"] =
            "llama-server не найден. Поставьте движок на этой странице или положите llama-server "
            + "из llama.cpp в PATH.",
        ["L_LocalLlamaFailed"] = "llama-server не запустился: {0}",
        ["L_LocalLlamaQuit"] = "llama-server сразу завершился — возможно, это не читаемый им файл модели.",
        ["L_LocalLlamaSlow"] = "llama-server не начал отвечать за минуту.",
        ["L_EngineMissing"] = "Ollama здесь ещё не установлена.",
        ["L_EngineNoAsset"] = "Не нашлось файла для скачивания движка.",
        ["L_EngineNoFinish"] = "Загрузка движка не завершилась. Ничего не сохранено.",
        ["L_EngineNoUnpack"] = "Движок не распаковался: {0}",
        ["L_EngineNoExe"] = "Архив распаковался, но ollama.exe в нём не оказалось.",
        ["L_ImageEngineNoExe"] = "Архив распаковался, но движка картинок (sd-cli.exe) в нём не оказалось.",
        ["L_EngineNoStart"] = "Ollama не запустилась: {0}",
        ["L_EngineQuit"] = "Ollama сразу завершилась — возможно, её порт занят чем-то другим.",
        ["L_EngineSlow"] = "Ollama не начала отвечать.",
        ["L_EngineNoRun"] = "Не удалось выполнить Ollama.",
        ["L_EngineListing"] = "Не удалось прочитать список релизов: {0}",
        ["L_LocalEngineInstall"] = "Поставить движок",
        ["L_LocalEngineStart"] = "Запустить движок",
        ["L_LocalEngineStop"] = "Остановить движок",
        ["L_LocalEngineStarting"] = "Запускаю движок…",
        ["L_LocalEngineFetching"] = "Качаю движок. Файл большой; можно оставить и заниматься своим.",
        ["L_LocalEngineIdle"] = "Движок установлен, но не запущен. Запустите его, чтобы загрузить модель.",
        ["L_LocalEngineAsk"] =
            "Скачать Ollama и распаковать в\n\n{0}\n\nОколо 1,4 ГБ, права администратора не "
            + "нужны. Скачанные модели лежат рядом, так что папку можно унести целиком.",
        ["L_LocalNoRunner"] =
            "Локальный движок не установлен. «Поставить движок» скачает Ollama в папку "
            + "программы; уже установленные Ollama или llama-server подхватятся сами.",
        ["L_AiAttachSsh"] = "Прикрепить SSH-подключение",
        ["L_AiAttachSshNote"] =
            "Агент получит хост, порт, учётную запись и туннели, чтобы писать команды для этой "
            + "машины, и будет знать, что работать нужно именно на ней.",
        ["L_AiSshSendSecret"] = "Передать и сохранённый пароль",
        ["L_AiSshSendSecretNote"] =
            "Пароль войдёт в текст сообщения и уйдёт на тот эндпоинт, которым пользуется этот "
            + "агент, — открытым текстом, и останется в его журналах. Включайте только для "
            + "эндпоинта, которому доверяете.",
        ["L_AiSshSecretSent"] = "пароль передан",
        ["L_Save"] = "Сохранить",
        ["L_Connect"] = "Подключиться",
        ["L_Remove"] = "Убрать",

        ["L_NewSshSessionHeader"] = "Новая SSH-сессия",
        ["L_EditSshSessionHeader"] = "Изменить SSH-сессию",
        ["L_PasteSshTip"] = "Заполнить из команды ssh в буфере обмена",
        ["L_FieldName"] = "ИМЯ",
        ["L_FieldHost"] = "ХОСТ",
        ["L_FieldPort"] = "ПОРТ",
        ["L_FieldUsername"] = "ПОЛЬЗОВАТЕЛЬ",
        ["L_FieldAuth"] = "АУТЕНТИФИКАЦИЯ",
        ["L_AuthPassword"] = "Пароль",
        ["L_AuthPrivateKey"] = "Приватный ключ",
        ["L_FieldPassword"] = "ПАРОЛЬ",
        ["L_PasswordDpapiNote"] = "Хранится в зашифрованном виде через Windows DPAPI под вашей учётной записью. Оставьте пустым, чтобы спрашивать при каждом подключении.",
        ["L_FieldKeyFile"] = "ФАЙЛ ПРИВАТНОГО КЛЮЧА",
        ["L_FieldPassphrase"] = "КЛЮЧЕВАЯ ФРАЗА",
        ["L_FieldTunnels"] = "ТУННЕЛИ",
        ["L_AddTunnelTip"] = "Добавить туннель",
        ["L_TunnelLocalPortTip"] = "Локальный порт для прослушивания",
        ["L_TunnelDestHostTip"] = "Целевой хост, как его видит удалённая сторона",
        ["L_TunnelDestPortTip"] = "Целевой порт",
        ["L_FieldConnection"] = "ПОДКЛЮЧЕНИЕ",
        ["L_AutoReconnect"] = "Переподключаться автоматически при обрыве",
        ["L_AutoReconnectNote"] = "Повторяет с растущей задержкой, до пяти раз. Сессия, продержавшаяся минуту, сбрасывает счётчик.",
        ["L_ErrClipboardRead"] = "Не удалось прочитать буфер обмена.",
        ["L_ErrClipboardEmpty"] = "Буфер обмена пуст. Сначала скопируйте команду ssh.",
        ["L_ErrNotSshCommand"] = "Это не похоже на команду ssh.",
        ["L_ErrHostRequired"] = "Укажите хост.",
        ["L_ErrUserRequired"] = "Укажите пользователя.",
        ["L_ErrPortRange"] = "Порт должен быть от 1 до 65535.",
        ["L_ErrChooseKey"] = "Выберите файл приватного ключа.",
        ["L_ErrKeyMissing"] = "Такого файла ключа не существует.",
        ["L_ErrTunnelIncomplete"] = "Туннель заполнен не полностью.",
        ["L_ErrTunnelDuplicate"] = "Два туннеля слушают один адрес {0}.",

        ["L_PasswordRequired"] = "Требуется пароль",

        ["L_PresentedFingerprint"] = "ПРЕДЪЯВЛЕННЫЙ ОТПЕЧАТОК",
        ["L_PreviouslyTrusted"] = "РАНЕЕ ДОВЕРЕННЫЙ ОТПЕЧАТОК",
        ["L_ConnectOnce"] = "Подключиться один раз",
        ["L_TrustRemember"] = "Доверять и запомнить",
        ["L_ReplaceStoredKey"] = "Заменить сохранённый ключ",
        ["L_CancelConnection"] = "Отменить подключение",
        ["L_HkUnknownServer"] = "Неизвестный сервер",
        ["L_HkNewKeyType"] = "Новый тип ключа для известного хоста",
        ["L_HkChanged"] = "Ключ хоста изменился",
        ["L_HkAlgoBits"] = "{0} · {1} бит",
        ["L_HkFirstBody"] = "RedBloom ещё не подключался к {0}, поэтому не может определить, тот ли это компьютер. Сверьте отпечаток с сервером, прежде чем доверять.",
        ["L_HkFirstHint"] = "На сервере `ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub` покажет отпечаток, который должен отображаться.",
        ["L_HkNewAlgoBody"] = "{0} уже в доверенных, но ещё ни разу не предъявлял ключ такого типа. Это нормально после перенастройки сервера — но так же выглядит и попытка перехвата. Сверьте отпечаток.",
        ["L_HkNewAlgoHint"] = "Если вы ничего не меняли на сервере, не доверяйте этому ключу.",
        ["L_HkChangedBody"] = "Ключ, предъявленный {0}, не совпадает с тем, которому RedBloom доверял раньше. Так бывает при пересборке сервера или смене ключей — но именно так выглядит и атака «человек посередине». Не продолжайте, пока не знаете, почему ключ изменился.",
        ["L_HkChangedHint"] = "Всё, что вы наберёте — включая пароли — уйдёт тому, кто владеет этим ключом.",
    };

    private static AppLanguage? _current;

    /// <summary>Raised after the language changes, for code that builds its own text.</summary>
    public static event Action? Changed;

    private static IReadOnlyDictionary<string, string> Table(AppLanguage language) =>
        language == AppLanguage.Russian ? Russian : English;

    /// <summary>Looks up a string in the current language, falling back to the key itself.</summary>
    public static string T(string key)
    {
        var table = Table(_current ?? AppLanguage.English);
        return table.TryGetValue(key, out var value) ? value : key;
    }

    /// <summary>
    /// Pushes the chosen language's strings into the application resources. A no-op when the
    /// language has not changed, so it is cheap to call from the shared apply path.
    /// </summary>
    public static void Apply(AppLanguage language)
    {
        if (_current == language)
        {
            return;
        }

        _current = language;

        var resources = Application.Current?.Resources;
        if (resources is null)
        {
            return;
        }

        // English is the full set of keys; writing over it each time keeps every key present
        // even if a translation is missing one.
        foreach (var (key, _) in English)
        {
            resources[key] = T(key);
        }

        Changed?.Invoke();
    }
}
